# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://githubpsyche.github.io/pcitpy/"

git_url = "https://github.com/githubpsyche/pcitpy/tree/master/"

def custom_doc_links(name): return None
