# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"run_importance_sampler": "00_Parameter_Configuration.ipynb",
         "preprocessing_setup": "01_Data_Preprocessing.ipynb",
         "scramble_dependent_variable": "01_Data_Preprocessing.ipynb",
         "importance_sampler": "02_Curve_Fitting.ipynb",
         "simulate_data": "04_Simulating_Data.ipynb",
         "likratiotest": "Additional_Helper_Functions.ipynb",
         "truncated_normal": "Additional_Helper_Functions.ipynb",
         "scale_data": "Additional_Helper_Functions.ipynb",
         "common_to_all_curves": "Common_To_All_Curves.ipynb",
         "initial_sampling": "Common_To_All_Curves.ipynb",
         "check_if_exceed_bound": "Common_To_All_Curves.ipynb",
         "curve_volumes": "Common_To_All_Curves.ipynb",
         "flip_vertical_params": "Common_To_All_Curves.ipynb",
         "sort_horizontal_params": "Common_To_All_Curves.ipynb",
         "draw_bcm_curve": "Common_To_All_Curves.ipynb",
         "auto_generate": "Common_To_All_Curves.ipynb",
         "weighted_curve": "Common_To_All_Curves.ipynb",
         "family_of_curves": "Family_of_Curves.ipynb",
         "horz_indpnt_curve": "Family_of_Curves.ipynb",
         "compute_horz_indpnt_likelihood": "Family_of_Curves.ipynb",
         "count_horz_indpnt_particles": "Family_of_Curves.ipynb",
         "get_horz_indpnt_curve_xy_vals": "Family_of_Curves.ipynb",
         "family_of_distributions": "Family_of_Distributions.ipynb",
         "bernoulli_distribution": "Family_of_Distributions.ipynb",
         "fminunc_bernoulli_both": "Family_of_Distributions.ipynb",
         "normal_distribution": "Family_of_Distributions.ipynb",
         "fminunc_normal_both": "Family_of_Distributions.ipynb"}

modules = ["pcitpy.py",
           "helpers.py",
           "common_to_all_curves.py",
           "family_of_curves.py",
           "family_of_distributions.py"]

doc_url = "https://githubpsyche.github.io/PCITpy/"

git_url = "https://github.com/githubpsyche/PCITpy/tree/master/"

def custom_doc_links(name): return None
