# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"family_of_distributions": "00_Family_of_Distributions.ipynb",
         "bernoulli_distribution": "00_Family_of_Distributions.ipynb",
         "fminunc_bernoulli_both": "00_Family_of_Distributions.ipynb",
         "normal_distribution": "00_Family_of_Distributions.ipynb",
         "fminunc_normal_both": "00_Family_of_Distributions.ipynb",
         "likratiotest": "00_Miscellaneous_Helper_Functions.ipynb",
         "truncated_normal": "00_Miscellaneous_Helper_Functions.ipynb",
         "scale_data": "00_Miscellaneous_Helper_Functions.ipynb",
         "family_of_curves": "01_Family_of_Curves.ipynb",
         "horz_indpnt_curve": "01_Family_of_Curves.ipynb",
         "compute_horz_indpnt_likelihood": "01_Family_of_Curves.ipynb",
         "count_horz_indpnt_particles": "01_Family_of_Curves.ipynb",
         "get_horz_indpnt_curve_xy_vals": "01_Family_of_Curves.ipynb",
         "common_to_all_curves": "02_Common_To_All_Curves.ipynb",
         "initial_sampling": "02_Common_To_All_Curves.ipynb",
         "check_if_exceed_bound": "02_Common_To_All_Curves.ipynb",
         "curve_volumes": "02_Common_To_All_Curves.ipynb",
         "flip_vertical_params": "02_Common_To_All_Curves.ipynb",
         "sort_horizontal_params": "02_Common_To_All_Curves.ipynb",
         "draw_bcm_curve": "02_Common_To_All_Curves.ipynb",
         "auto_generate": "02_Common_To_All_Curves.ipynb",
         "weighted_curve": "02_Common_To_All_Curves.ipynb",
         "preprocessing_setup": "02_Data_Preprocessing.ipynb",
         "scramble_dependent_variable": "02_Data_Preprocessing.ipynb",
         "importance_sampler": "03_Curve_Fitting.ipynb",
         "run_importance_sampler": "04_Parameter_Configuration.ipynb",
         "simulate_data": "Simulating_Data.ipynb"}

modules = ["family_of_distributions.py",
           "helpers.py",
           "family_of_curves.py",
           "common_to_all_curves.py",
           "pcitpy.py"]

doc_url = "https://githubpsyche.github.io/pcitpy/"

git_url = "https://github.com/githubpsyche/pcitpy/tree/master/"

def custom_doc_links(name): return None
