# AUTOGENERATED! DO NOT EDIT! File to edit: 00_Helper_Functions.ipynb (unless otherwise specified).

__all__ = ['likratiotest']

# Cell
from scipy import stats


def likratiotest(l1, l0, k1, k0):
    D = -2 * (l0 - l1)  # deviance score
    df = k1 - k0  # degrees of freedom
    p = stats.chi2.sf(D, df)  # chi-square test
    return D, p