# AUTOGENERATED! DO NOT EDIT! File to edit: 02_Curve_Fitting.ipynb (unless otherwise specified).

__all__ = ['importance_sampler']

# Cell

def importance_sampler(raw_data, analysis_settings):
   """
   Recovers a curve that best explains the relationship between the predictor and dependent variables

   **Arguments**:
   - raw_data: The data matrix (total number of trials x 6 columns). Refer to RUN_IMPORTANCE_SAMPLER()
   - analysis_settings: A struct that holds algorithm relevant settings. Refer to RUN_IMPORTANCE_SAMPLER()

    Saves a .mat file in `current_path/analysis_id/analysis_id_importance_sampler.mat`
   """
   pass